name: Publish

on:
    workflow_dispatch:

concurrency: publish

permissions:
    contents: write
    id-token: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - uses: denoland/setup-deno@v2

            - uses: actions/setup-node@v6
              with:
                  node-version: lts/*

            - run: git config user.name "github-actions[bot]"

            - run: git config user.email "github-actions[bot]@users.noreply.github.com"

            - run: npm install

            - run: npm version patch

            - run: npm publish

            - run: git push --tags
